require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'YohaKitError' do
  config = use_native_modules!
  $RNFirebaseAnalyticsWithoutAdIdSupport=true

  use_react_native!(:path => config["reactNativePath"])


  target 'YohaKitErrorTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'AppAuth', '1.4.0'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.6.10', 'Flipper' => '0.147.0', 'Flipper-RSocket' => '1.4.3' })
end
